{% set name = "coppeliasim-zmqremoteapi-client" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coppeliasim_zmqremoteapi_client-{{ version }}.tar.gz
  sha256: a97cfe1510e1a41cdabe829efb6e0e0aa58f0612938c839bc3780e0f9c794f7a
  patches:
    - fix-cbor2-req.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pyzmq
    - cbor2

test:
  imports:
    - coppeliasim_zmqremoteapi_client
  commands:
    - pip check
    - python -c "from coppeliasim_zmqremoteapi_client import RemoteAPIClient; client = RemoteAPIClient()"
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Client for the CoppeliaSim's zmqRemoteApi (protocol version 2)
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://manual.coppeliarobotics.com/en/zmqRemoteApiOverview.htm

extra:
  recipe-maintainers:
    - Tobias-Fischer
